image: node:20

stages:
  - install
  - build
  - test

jobs:
  run-install:
    stage: install
    script:
      - npm install

  run-build:
    stage: build
    script:
      - npx tsc --noEmit

  run-test:
    stage: test
    script:
      - npm run test:run