image: node:20

stages:
  - install
  - build
  - test

jobs:
  install:
    stage: install
    scripts:
      - step: npm install

  build:
    stage: build
    scripts:
      - step: npx tsc --noEmit

  test:
    stage: test
    scripts:
      - step: npm run test:run