image: node:20

stages:
  - install
  - build
  - test

install_deps:
  stage: install
  tags:
    - docker
  script:
    - npm install

build_app:
  stage: build
  tags:
    - docker
  script:
    - npx tsc --noEmit

test_app:
  stage: test
  tags:
    - docker
  script:
    - npm run test:run