name: CI

on:
  push:
    branches: [master, lab89]
  pull_request:
    branches: [master, lab89]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run test:run
      - run: npm run build